### ISSUE TITLE
Doesn´t support decimal numbers?

### ISSUE THREAD

**Issue by luiyeas** [NaturalizerINA/AndroidNumberSeparator#1]
Doesn´t support decimal numbers?

**Comment by NaturalizerINA** [comment]
That is true, this library doesn't support decimal numbers for now, but doesn't rule out the possibility for supprting the decimal numbers for the future update, may be It's not an issue, but an feedback for me, thanks for the feedback luiyeas :+1:

**Comment by NaturalizerINA** [comment]
You can update the latest dependency :+1:
